#!/usr/bin/env node
/**
 * build-context.mjs — regenerate repo-context.generated.js
 *
 * For every project node on the practice map (the 'technology' elements in
 * docs/_data/entities.json that carry a GitHub url), fetch its README, file
 * tree and language breakdown from the GitHub API and bake them into a single
 * ES module the Worker imports. When a visitor has a project node in focus,
 * the Worker injects THAT repo's bundle into the system prompt, so the chat
 * can talk about the project with real depth instead of a one-line blurb.
 *
 * Auth:  uses your existing `gh` login token — no separate secret needed.
 * Run:   node build-context.mjs        (from chat-worker/)
 * Then:  npx wrangler deploy            (bakes the refreshed data into the Worker)
 */

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENTITIES = join(__dirname, '..', 'docs', '_data', 'entities.json');
const OUT = join(__dirname, 'repo-context.generated.js');

// Keep the baked bundle small and the injected context focused.
const README_MAX_CHARS = 8000;
const TREE_MAX_ENTRIES = 250;
const SKIP_DIR =
  /(^|\/)(node_modules|\.git|__pycache__|\.venv|venv|dist|build|\.next|\.cache|\.turbo|coverage|\.idea)(\/|$)/;

let token;
try {
  token = execSync('gh auth token', { encoding: 'utf8' }).trim();
} catch {
  console.error('Could not get a GitHub token. Run `gh auth login` first.');
  process.exit(1);
}

async function gh(path, { raw = false } = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: raw ? 'application/vnd.github.raw' : 'application/vnd.github+json',
      'User-Agent': 'kgk-build-context',
      'X-GitHub-Api-Version': '2022-11-28',
    },
  });
  if (!res.ok) return { ok: false, status: res.status };
  return { ok: true, data: raw ? await res.text() : await res.json() };
}

function ownerRepo(url) {
  const m = url.match(/github\.com\/([^/]+)\/([^/]+?)(?:\.git)?\/?$/);
  if (!m) throw new Error(`unparseable repo url: ${url}`);
  return { owner: m[1], repo: m[2] };
}

// Prune noise, cap length, render as an indented tree the model can read.
function renderTree(entries) {
  const kept = entries
    .filter((e) => e.type === 'blob' && !SKIP_DIR.test(e.path))
    .map((e) => e.path)
    .sort();
  const shown = kept.slice(0, TREE_MAX_ENTRIES);
  const lines = shown.map((p) => {
    const depth = p.split('/').length - 1;
    return `${'  '.repeat(depth)}${p.split('/').pop()}`;
  });
  if (kept.length > TREE_MAX_ENTRIES) {
    lines.push(`… (+${kept.length - TREE_MAX_ENTRIES} more files)`);
  }
  return lines.join('\n');
}

function stackLine(languages) {
  const entries = Object.entries(languages || {});
  if (!entries.length) return 'n/a';
  const total = entries.reduce((sum, [, bytes]) => sum + bytes, 0);
  return entries
    .sort((a, b) => b[1] - a[1])
    .map(([lang, bytes]) => `${lang} ${Math.round((bytes / total) * 100)}%`)
    .join(', ');
}

const entities = JSON.parse(readFileSync(ENTITIES, 'utf8'));
const projects = entities.elements.filter((e) => e.type === 'technology' && e.url);

const context = {};
const summary = [];

for (const p of projects) {
  const { owner, repo } = ownerRepo(p.url);
  const [readmeRes, treeRes, langRes] = await Promise.all([
    gh(`/repos/${owner}/${repo}/readme`, { raw: true }),
    gh(`/repos/${owner}/${repo}/git/trees/HEAD?recursive=1`),
    gh(`/repos/${owner}/${repo}/languages`),
  ]);

  let readme = readmeRes.ok ? readmeRes.data.trim() : '';
  if (readme.length > README_MAX_CHARS) {
    readme = readme.slice(0, README_MAX_CHARS) + '\n\n… (README truncated)';
  }
  const tree = treeRes.ok ? renderTree(treeRes.data.tree || []) : '';
  const stack = langRes.ok ? stackLine(langRes.data) : 'n/a';

  context[p.id] = { label: p.label, repo: `${owner}/${repo}`, url: p.url, stack, readme, tree };
  summary.push(
    `  ${p.id.padEnd(28)} readme:${String(readme.length).padStart(5)}c  ` +
      `tree:${String(tree ? tree.split('\n').length : 0).padStart(3)}l  stack:[${stack}]`
  );
  if (!readmeRes.ok) console.warn(`  ! ${p.id}: no README (${readmeRes.status})`);
}

const banner =
  '// AUTO-GENERATED by build-context.mjs — do not edit by hand.\n' +
  '// Regenerate: node build-context.mjs   (then: npx wrangler deploy)\n';
writeFileSync(OUT, `${banner}export const REPO_CONTEXT = ${JSON.stringify(context, null, 2)};\n`);

console.log(`\nWrote ${OUT}`);
console.log(`Baked ${projects.length} project bundles:\n`);
console.log(summary.join('\n'));
